import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header & Navigation
    'header.import': 'Import CSV',
    'header.oui': 'IEEE OUI Registry',
    'header.addCsv': 'Add CSV File',
    'header.mainMenu': 'Main Menu',

    // Status Bar
    'status.totalRecords': 'captures in total',

    // KPIs
    'kpi.uniqueNetworks': 'Unique Networks',
    'kpi.uniqueSsids': 'Unique SSIDs',
    'kpi.hiddenSsids': 'hidden SSIDs',
    'kpi.withEncryption': 'With Encryption',
    'kpi.detectedVendors': 'Detected manufacturers',
    'kpi.manufacturers': 'Identified manufacturers',
    'kpi.wpsEnabled': 'With WPS',
    'kpi.withWps': 'of detected networks have the WPS function enabled',

    // Dashboard Sections
    'dashboard.statsTitle': 'Statistics and Summary of Detected Networks',
    'dashboard.filterActive': 'FILTERED',
    'dashboard.mapTitle': 'Interactive Map',
    'dashboard.tableTitle': 'List of detected networks',
    'dashboard.securityBreakdown': 'Security / Encryption Breakdown',
    'dashboard.vendorBreakdown': 'Top Detected Manufacturers',

    // Table
    'table.colSsid': 'SSID',
    'table.colMac': 'BSSID / MAC',
    'table.colVendor': 'Manufacturer',
    'table.colSecurity': 'Security',
    'table.colChannel': 'Channel',
    'table.colSignal': 'Signal',
    'table.colFirstSeen': 'First Seen',
    'table.colDetections': 'Detections',
    'table.colActions': 'Actions',
    'table.btnMap': 'Map',
    'table.btnDetails': 'Details',
    'table.unassigned': '[Unassigned by IEEE]',

    // Inspector Details Modal
    'modal.hardwareVendor': 'Manufacturer',
    'modal.securityEncryption': 'Security / Encryption',
    'modal.keyMgmt': 'Authentication and Key Management (AKM)',
    'modal.technicalAnalysis': 'Technical Analysis & Encryption Breakdown (Generated by AI)',
    'modal.pmfRequired': 'PMF 802.11w: Required (MFPR)',
    'modal.pmfCapable': 'PMF 802.11w: Supported (MFPC)',
    'modal.fastRoaming': 'Fast Roaming: 802.11r (FT)',
    'modal.wpsActive': 'WPS Active',
    'modal.geoPositionTriangulated': 'Estimated Location from Triangulation',
    'modal.geoPositionSingle': 'GPS coordinates of the detection',
    'modal.copySummary': 'Copy Summary',
    'modal.centerMap': 'Center on Map',
    'modal.close': 'Close',
  },
  fr: {
    // Header & Navigation
    'header.import': 'Importer CSV',
    'header.oui': 'Base de données OUI',
    'header.addCsv': 'Ajouter un fichier CSV',
    'header.mainMenu': 'Menu principal',

    // Status Bar
    'status.totalRecords': 'captures au total',

    // KPIs
    'kpi.uniqueNetworks': 'Réseaux Uniques',
    'kpi.uniqueSsids': 'Noms de réseaux uniques',
    'kpi.hiddenSsids': 'noms de réseaux masqués',
    'kpi.withEncryption': 'Avec Chiffrement',
    'kpi.detectedVendors': 'Fabricants Détectés',
    'kpi.manufacturers': 'Fabricants identifiés',
    'kpi.wpsEnabled': 'Avec WPS',
    'kpi.withWps': 'des réseaux détectés ont la fonction WPS activée',

    // Dashboard Sections
    'dashboard.statsTitle': 'Statistiques & Synthèse des réseaux détectés',
    'dashboard.filterActive': 'FILTRÉ',
    'dashboard.mapTitle': 'Carte Interactive',
    'dashboard.tableTitle': 'Liste des réseaux détectés',
    'dashboard.securityBreakdown': 'Répartition des types de chiffrement',
    'dashboard.vendorBreakdown': 'Principaux fabricants détectés',

    // Table
    'table.colSsid': 'SSID',
    'table.colMac': 'BSSID / MAC',
    'table.colVendor': 'Fabricant',
    'table.colSecurity': 'Sécurité',
    'table.colChannel': 'Canal',
    'table.colSignal': 'Signal',
    'table.colFirstSeen': '1ère Détection',
    'table.colDetections': 'Détections',
    'table.colActions': 'Actions',
    'table.btnMap': 'Carte',
    'table.btnDetails': 'Détails',
    'table.unassigned': "[Non assigné par l'IEEE]",

    // Inspector Details Modal
    'modal.hardwareVendor': 'Fabricant',
    'modal.securityEncryption': 'Sécurité / Chiffrement',
    'modal.keyMgmt': 'Authentification et gestion des clés (AKM)',
    'modal.technicalAnalysis': 'Analyse technique & description du chiffrement (Générée par IA)',
    'modal.pmfRequired': 'PMF 802.11w\u00A0: Obligatoire (MFPR)',
    'modal.pmfCapable': 'PMF 802.11w\u00A0: Supporté (MFPC)',
    'modal.fastRoaming': 'Fast Roaming\u00A0: 802.11r (FT)',
    'modal.wpsActive': 'WPS Activé',
    'modal.geoPositionTriangulated': 'Localisation estimée par triangulation',
    'modal.geoPositionSingle': 'Coordonnées GPS de la détection',
    'modal.copySummary': 'Copier le résumé',
    'modal.centerMap': 'Centrer sur la carte',
    'modal.close': 'Fermer',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const stored = localStorage.getItem('wigle_analyzer_lang');
      if (stored === 'fr' || stored === 'en') return stored;
    } catch {
      // ignore
    }
    return 'en'; // Default is English as requested
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('wigle_analyzer_lang', lang);
    } catch {
      // ignore
    }
  };

  const toggleLanguage = () => {
    setLanguage(language === 'en' ? 'fr' : 'en');
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
